#!/usr/bin/env python3
"""
sync_tables.py -- generates modules/<name>/table_core.py from a live
database reflection of that module's schema.sql.

WHY THIS EXISTS:
schema.sql is the one hand-written source of truth for a module's table
structure (it's also what Ansible applies during provisioning). Rather
than hand-writing a matching SQLAlchemy Core Table() object -- which
would mean maintaining the same structure in two places by hand, an easy
way for the two to drift out of sync -- this script connects to a real
Postgres database where schema.sql has already been applied, reads back
the actual table structure, and writes it out as a plain committed
Python file.

This is a BUILD-TIME step, not something the app does on every boot.
Run it once after writing/changing a module's schema.sql (or let
setup.py call it for you as part of app bring-up). The generated file is
gitignored-free -- it IS meant to be committed -- but it's marked
AUTO-GENERATED and should never be hand-edited; re-run this script
instead.

USAGE:
    python sync_tables.py --module=equipment --db-url=postgresql://...
    python sync_tables.py --all --db-url=postgresql://...
    python sync_tables.py --module=equipment --apply-schema --db-url=...
    python sync_tables.py --module=equipment --dry-run --db-url=...

If --db-url is omitted, falls back to DATABASE_URL built the same way
db.py builds it (from .env's DB_* vars).
"""

import argparse
import sys
from pathlib import Path

from sqlalchemy import create_engine, MetaData, text
from sqlalchemy.engine import Engine

PROJECT_ROOT = Path(__file__).resolve().parents[2]
MODULES_DIR = PROJECT_ROOT / "modules"

# Maps SQLAlchemy's generic reflected type names to the import + source
# text we want in the generated file. Kept small and explicit rather than
# trying to auto-map every possible Postgres type -- if a module needs a
# type not listed here, that's a deliberate signal to extend this map,
# not something that should silently produce wrong output.
_TYPE_MAP = {
    "INTEGER": "Integer",
    "BIGINT": "BigInteger",
    "SMALLINT": "SmallInteger",
    "TEXT": "Text",
    "VARCHAR": "String",
    "BOOLEAN": "Boolean",
    "NUMERIC": "Numeric",
    "TIMESTAMP": "DateTime(timezone=True)",
    "DATE": "Date",
}


# --- segment: schema loading -------------------------------------------------

def load_module_schema(module_name: str) -> str:
    schema_path = MODULES_DIR / module_name / "schema.sql"
    if not schema_path.exists():
        raise FileNotFoundError(f"modules/{module_name}/schema.sql not found")
    return schema_path.read_text()


# --- segment: connection ------------------------------------------------------

def get_engine(db_url: str | None) -> Engine:
    if db_url is None:
        # Reuse db.py's own URL-building logic instead of duplicating it.
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from db import build_database_url
        db_url = build_database_url()
    return create_engine(db_url)


# --- segment: schema application (optional) -----------------------------------

def apply_schema_if_needed(engine: Engine, schema_sql: str, apply: bool):
    if not apply:
        return
    with engine.begin() as conn:
        conn.execute(text(schema_sql))


# --- segment: reflection -------------------------------------------------------

def reflect_table(engine: Engine, table_name: str):
    metadata = MetaData()
    metadata.reflect(bind=engine, only=[table_name])
    if table_name not in metadata.tables:
        raise RuntimeError(
            f"Table '{table_name}' not found in the database. Apply "
            f"schema.sql first (or pass --apply-schema)."
        )
    return metadata.tables[table_name]


# --- segment: code generation ---------------------------------------------------

def _column_source(col) -> str:
    raw_type = str(col.type).split("(")[0].upper()
    sa_type = _TYPE_MAP.get(raw_type, "Text")  # unknown types fall back to Text, not a crash
    parts = [f'Column("{col.name}", {sa_type}']
    if col.primary_key:
        parts.append("primary_key=True")
    elif not col.nullable:
        parts.append("nullable=False")
    parts_str = ", ".join(parts)
    return f"    {parts_str}),"


def generate_core_file(table, module_name: str) -> str:
    columns_src = "\n".join(_column_source(c) for c in table.columns)
    return f'''# AUTO-GENERATED by core/backend/sync_tables.py from a live reflection of
# modules/{module_name}/schema.sql. Do not hand-edit -- re-run
# sync_tables.py after changing schema.sql instead, or this file will be
# silently out of date with the real database.
from sqlalchemy import (
    Table, Column, MetaData,
    Integer, BigInteger, SmallInteger, Text, String, Boolean,
    Numeric, DateTime, Date,
)

metadata = MetaData()

table = Table(
    "{table.name}",
    metadata,
{columns_src}
)
'''


# --- segment: main ---------------------------------------------------------------

def sync_one(module_name: str, engine: Engine, apply_schema: bool, dry_run: bool):
    schema_sql = load_module_schema(module_name)
    apply_schema_if_needed(engine, schema_sql, apply_schema)
    table = reflect_table(engine, _table_name_from_schema(schema_sql, module_name))
    source = generate_core_file(table, module_name)

    out_path = MODULES_DIR / module_name / "table_core.py"
    if dry_run:
        print(f"--- {out_path} (dry run, not written) ---")
        print(source)
    else:
        out_path.write_text(source)
        print(f"Wrote {out_path}")


def _table_name_from_schema(schema_sql: str, module_name: str) -> str:
    """Best-effort pull of the table name out of schema.sql's first
    CREATE TABLE statement, so the person running this doesn't have to
    also pass --table separately when it's already unambiguous. Falls
    back to the module name if it can't find one."""
    import re
    match = re.search(r"CREATE TABLE\s+(?:IF NOT EXISTS\s+)?(\w+)", schema_sql, re.IGNORECASE)
    return match.group(1) if match else module_name


def main():
    parser = argparse.ArgumentParser(
        description="Generate modules/<name>/table_core.py from a live DB reflection."
    )
    parser.add_argument("--module", help="Sync a single module by name")
    parser.add_argument("--all", action="store_true", help="Sync every module under modules/")
    parser.add_argument("--db-url", default=None, help="Postgres URL (defaults to .env's DB_* vars)")
    parser.add_argument("--apply-schema", action="store_true",
                         help="Run schema.sql against the DB first, if the table doesn't exist yet")
    parser.add_argument("--dry-run", action="store_true", help="Print the generated file instead of writing it")
    args = parser.parse_args()

    if not args.module and not args.all:
        parser.error("Specify --module=<name> or --all")

    engine = get_engine(args.db_url)

    module_names = (
        [args.module] if args.module
        else [p.name for p in MODULES_DIR.iterdir() if p.is_dir() and (p / "schema.sql").exists()]
    )

    for name in module_names:
        sync_one(name, engine, args.apply_schema, args.dry_run)


if __name__ == "__main__":
    main()
