# AUTO-GENERATED by core/backend/sync_tables.py from a live reflection of
# modules/recipe/schema.sql. Do not hand-edit -- re-run
# sync_tables.py after changing schema.sql instead, or this file will be
# silently out of date with the real database.
from sqlalchemy import (
    Table, Column, MetaData,
    Integer, BigInteger, SmallInteger, Text, String, Boolean,
    Numeric, DateTime, Date,
)

metadata = MetaData()

table = Table(
    "recipe",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("menu_item_product_id", Integer, nullable=False),
    Column("ingredient_product_id", Integer, nullable=False),
    Column("quantity_required", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)
