# AUTO-GENERATED by core/backend/sync_tables.py from a live reflection of
# modules/equipment/schema.sql. Do not hand-edit -- re-run
# sync_tables.py after changing schema.sql instead, or this file will be
# silently out of date with the real database.
from sqlalchemy import (
    Table, Column, MetaData,
    Integer, BigInteger, SmallInteger, Text, String, Boolean,
    Numeric, DateTime, Date,
)

metadata = MetaData()

table = Table(
    "equipment",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", Text, nullable=False),
    Column("category", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("location", Text),
    Column("serial_number", Text),
    Column("quantity", Integer, nullable=False),
    Column("notes", Text),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)
