# AUTO-GENERATED by core/backend/sync_tables.py from a live reflection of
# modules/sale_item/schema.sql. Do not hand-edit -- re-run
# sync_tables.py after changing schema.sql instead, or this file will be
# silently out of date with the real database.
from sqlalchemy import (
    Table, Column, MetaData,
    Integer, BigInteger, SmallInteger, Text, String, Boolean,
    Numeric, DateTime, Date,
)

metadata = MetaData()

table = Table(
    "sale_item",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("sale_id", Integer, nullable=False),
    Column("product_id", Integer, nullable=False),
    Column("quantity", Integer, nullable=False),
    Column("unit_price_at_sale", Numeric, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)
